### ISSUE TITLE
 Empty string title at 0. Title strings must have a length greater than zero

### ISSUE THREAD

**Issue by erikanderson** [example42/puppet-mongodb#7]
puppet 3.8.2 `stringify_facts = false` `parser = future`

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Empty string title at 0. Title strings must have a length greater than zero. at /modules/mongodb/manifests/keyfile.pp:13:10 

The file in question: 

``` puppet
# = Class: mongodb::keyfile
#
# This class installs mongodb::keyfile. It's included by the main mongodb class
#
class mongodb::keyfile {

  exec { 'generate_mongo_keyfile':
    command => "openssl rand -base64 753 > ${mongodb::keyfile}",
    path    => '/usr/bin:/bin:/usr/sbin:/sbin',
    creates => $mongodb::keyfile,
    notify  => Service['mongodb'],
  }
  file { $mongodb::keyfile:
    ensure  => present,
    mode    => '0600',
    owner   => $mongodb::process_user,
    group   => $mongodb::process_user,
    require => Exec['generate_mongo_keyfile'],
  }
}
```

**Comment by alvagante** [comment]
Uhm , 
it looks like keyfile variable or param is not set anywhere in the mongodb class.
Should be added there with a correct path
