### ISSUE TITLE
Parameter noop failed on Package[mongodb]: Invalid value ""

### ISSUE THREAD

**Issue by erikanderson** [example42/puppet-mongodb#8]
puppet 3.8.2 `stringify_facts = false` `parser = future`

Error: Failed to apply catalog: Parameter noop failed on Package[mongodb]: Invalid value "". Valid values are true, false.  at /modules/mongodb/manifests/server.pp:7

**Comment by erikanderson** [comment]
I fixed this temporarily by setting `  $noops = false` in params.pp. I feel like this would be a sensible default

**Comment by alvagante** [comment]
Actually this whole noops thing has not been good idea.
You solution works but is dangerous, as it ignores an eventuall --noop option passed via the command line. I'd rather remove any reference to this noop parameter in the class.
As done here:
https://github.com/example42/puppet-logrotate/commit/5372c8a3185ce3a60cce593c830917cef8e92b3c

(PR welcomed)
